title: "Clara Ortega de San Luis Lab"
email: "clara@example.com"
description: >-
  Research group led by Clara Ortega de San Luis.
baseurl: ""
url: "https://claraortegadesanluis.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache