title: Clara Ortega de San Luis Lab
description: Cognitive Neuroscience & Brain Dynamics
baseurl: ""
url: "https://claraortegadesanluis.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Clara Ortega de San Luis"

logo: "/assets/images/university1-logo.png"

minimal_mistakes_skin: "default"
search: true

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

nav:
  - Home: /
  - Research: /research/
  - Publications: /publications/
  - Team: /team/
  - Join: /join/
  - Contact: /contact/